# Generated by Django 2.1.7 on 2019-10-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191013_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_hi',
            field=models.TextField(null=True),
        ),
    ]
