# Generated by Django 2.1.7 on 2019-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191020_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='answer1_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='answer1_hi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='answer2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='answer2_hi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
